"""Add AudioProcessingJob and TabGeneration models

Revision ID: 1042bf3fcc1e
Revises: 5e5338ef951b
Create Date: 2025-10-20 22:59:46.313089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1042bf3fcc1e'
down_revision = '5e5338ef951b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_processing_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('source_info', sa.String(length=255), nullable=True),
    sa.Column('midi_relative_path', sa.String(length=255), nullable=True),
    sa.Column('wav_relative_path', sa.String(length=255), nullable=True),
    sa.Column('midi_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_hash', name='_user_source_uc')
    )
    with op.batch_alter_table('audio_processing_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_processing_job_source_hash'), ['source_hash'], unique=False)

    op.create_table('tab_generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=True),
    sa.Column('tab_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['audio_processing_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tab_generation')
    with op.batch_alter_table('audio_processing_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_processing_job_source_hash'))

    op.drop_table('audio_processing_job')
    # ### end Alembic commands ###
